apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: extensions.extensions.crossplane.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.conditions[?(@.type=="Ready")].status
    name: READY
    type: string
  - JSONPath: .spec.version
    name: VERSION
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  group: extensions.crossplane.io
  names:
    kind: Extension
    plural: extensions
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            company:
              type: string
            controller:
              properties:
                deployment:
                  properties:
                    name:
                      type: string
                    spec:
                      type: object
                  required:
                  - name
                  - spec
                  type: object
              type: object
            customresourcedefinitions:
              properties:
                dependsOn:
                  description: DependsOn is the list of CRDs that this extension depends
                    on. This data drives the dependency resolution process.
                  items:
                    type: object
                  type: array
                owns:
                  description: Owned is the list of CRDs that this extension defines
                    and owns
                  items:
                    type: object
                  type: array
              type: object
            description:
              type: string
            icons:
              items:
                properties:
                  mediatype:
                    type: string
                required:
                - mediatype
                type: object
              type: array
            keywords:
              items:
                type: string
              type: array
            license:
              type: string
            links:
              items:
                properties:
                  description:
                    type: string
                  url:
                    type: string
                required:
                - url
                type: object
              type: array
            maintainers:
              items:
                properties:
                  email:
                    type: string
                  name:
                    type: string
                type: object
              type: array
            owners:
              items:
                properties:
                  email:
                    type: string
                  name:
                    type: string
                type: object
              type: array
            permissions:
              properties:
                rules:
                  items:
                    type: object
                  type: array
              type: object
            title:
              type: string
            version:
              type: string
          type: object
        status:
          properties:
            controllerRef:
              type: object
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
