apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: extensionrequests.extensions.crossplane.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.conditions[?(@.type=="Ready")].status
    name: READY
    type: string
  - JSONPath: .spec.source
    name: SOURCE
    type: string
  - JSONPath: .spec.package
    name: PACKAGE
    type: string
  - JSONPath: .spec.crd
    name: CRD
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  group: extensions.crossplane.io
  names:
    kind: ExtensionRequest
    plural: extensionrequests
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            crd:
              description: CustomResourceDefinition is the full name of a CRD that
                is owned by the extension being requested. This can be a convenient
                way of installing an extension when the desired CRD is known, but
                the package name that contains it is not known. Either Package or
                CustomResourceDefinition can be specified.
              type: string
            package:
              description: Package is the name of the extension package that is being
                requested, e.g., myapp. Either Package or CustomResourceDefinition
                can be specified.
              type: string
            source:
              description: Source is the domain name for the extension registry hosting
                the extension being requested, e.g., registry.crossplane.io
              type: string
          type: object
        status:
          properties:
            extensionRecord:
              type: object
            installJob:
              type: object
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
