{{- if .Capabilities.APIVersions.Has "cilium.io/v2/CiliumNetworkPolicy" -}}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-apiserver-access
  namespace: {{ .Release.Namespace | quote }}
spec:
  egress:
  - toEntities:
    - kube-apiserver
  endpointSelector: {}
{{- end }}
