{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" -}}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ template "crossplane.name" . }}-psp
  labels:
    app: {{ template "crossplane.name" . }}
    release: {{ .Release.Name }}
    {{- include "crossplane.labels" . | indent 4 }}
  {{- with .Values.customAnnotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  privileged: false
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  runAsUser:
    rule: MustRunAsNonRoot
  runAsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - 'secret'
    - 'configMap'
    - 'emptyDir'
    - 'projected'
  allowPrivilegeEscalation: false
  hostNetwork: false
  hostIPC: false
  hostPID: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "crossplane.name" . }}-use-psp
  labels:
    app: {{ template "crossplane.name" . }}
    {{- include "crossplane.labels" . | indent 4 }}
  {{- with .Values.serviceAccount.customAnnotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - {{ template "crossplane.name" . }}-psp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "crossplane.name" . }}-use-psp
  labels:
    app: {{ template "crossplane.name" . }}
    {{- include "crossplane.labels" . | indent 4 }}
  {{- with .Values.serviceAccount.customAnnotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace | quote }}
    name: {{ template "crossplane.name" . }}
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace | quote }}
    name: rbac-manager
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace | quote }}
    name: {{ include "crdInstall" . }}
roleRef:
  kind: ClusterRole
  name: {{ template "crossplane.name" . }}-use-psp
  apiGroup: rbac.authorization.k8s.io
{{- end }}
