{{ if eq (include "resource.vpa.enabled" .) "true" }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ template "crossplane.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: {{ .Chart.Name }}
        controlledValues: RequestsAndLimits
        maxAllowed:
          memory: {{ .Values.giantswarm.verticalPodAutoscaler.crossplane.limits.memory }}
        mode: Auto
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "crossplane.name" . }}
  updatePolicy:
    updateMode: Auto
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ template "crossplane.name" . }}-rbac-manager
  namespace: {{ .Release.Namespace }}
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: {{ .Chart.Name }}
        controlledValues: RequestsAndLimits
        maxAllowed:
          memory: {{ .Values.giantswarm.verticalPodAutoscaler.rbacManager.limits.memory }}
        mode: Auto
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "crossplane.name" . }}-rbac-manager
  updatePolicy:
    updateMode: Auto
{{ end }}
