{{- range $key, $val := .Values.clusterStacks }}
{{- if $val.deploy }}
apiVersion: stacks.crossplane.io/v1alpha1
kind: ClusterStackInstall
metadata:
  name: "provider-{{ $key }}"
spec:
  package: "crossplane/provider-{{ $key }}:{{ $val.version }}"
---
{{- end }}
{{- end }}