apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
- apiGroups:
  - cache.crossplane.io
  - compute.crossplane.io
  - database.crossplane.io
  - core.crossplane.io
  - stacks.crossplane.io
  - storage.crossplane.io
  - aws.crossplane.io
  - cache.aws.crossplane.io
  - compute.aws.crossplane.io
  - database.aws.crossplane.io
  - storage.aws.crossplane.io
  - azure.crossplane.io
  - cache.azure.crossplane.io
  - compute.azure.crossplane.io
  - database.azure.crossplane.io
  - network.azure.crossplane.io
  - storage.azure.crossplane.io
  - gcp.crossplane.io
  - cache.gcp.crossplane.io
  - compute.gcp.crossplane.io
  - database.gcp.crossplane.io
  - servicenetworking.gcp.crossplane.io
  - storage.gcp.crossplane.io
  - workload.crossplane.io
  resources:
  - "*"
  verbs:
  - "*"
