apiVersion: v1
kind: ServiceAccount
metadata:
  name: package-manager
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
