{{- if .Values.webhooks.enabled }}
# The reason this is created empty and filled by the init container is that it's
# mounted by the actual container, so if it wasn't created by Helm, then the
# deployment wouldn't be deployed at all with secret to mount not found error.
apiVersion: v1
kind: Secret
metadata:
  name: webhook-tls-secret
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""
{{- end }}