{{- if ne .Values.webhook.tlsSecretName "" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "crossplane.name" . }}-webhooks
  labels:
    app: {{ template "crossplane.name" . }}
    release: {{ .Release.Name }}
    {{- include "crossplane.labels" . | indent 4 }}
spec:
  selector:
    app: {{ template "crossplane.name" . }}
    release: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 6443
    targetPort: 6443
{{- end }}