apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: azurebuckets.storage.azure.crossplane.io
spec:
  group: storage.azure.crossplane.io
  names:
    kind: AzureBucket
    plural: azurebuckets
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            accessTier:
              description: AccessTier hot or cold
              type: string
            connectionSecretNameOverride:
              type: string
            location:
              type: string
            name:
              type: string
            predefinedACL:
              description: 'PredefinedACL One of: private, full-public-read, public-read-blobs-only'
              type: string
            providerRef:
              type: object
            storage:
              description: 'Storage One of: Locally redundant storage (LRS) Geo-redundant
                storage (GRS) Read-access geo-redundant storage (RA-GRS)'
              type: string
          required:
          - providerRef
          type: object
        status:
          properties:
            connectionSecretRef:
              description: the external ID to identify this resource in the cloud
                provider
              type: object
            message:
              type: string
            providerID:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
