apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: azurebuckets.storage.azure.crossplane.io
spec:
  group: storage.azure.crossplane.io
  names:
    kind: AzureBucket
    plural: azurebuckets
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            accessTier:
              type: string
            connectionSecretNameOverride:
              type: string
            location:
              type: string
            name:
              type: string
            predefinedACL:
              type: string
            providerRef:
              type: object
            storage:
              type: string
          required:
          - providerRef
          type: object
        status:
          properties:
            connectionSecretRef:
              type: object
            message:
              type: string
            providerID:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
