apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: rdsinstances.database.aws.crossplane.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.state
    name: STATUS
    type: string
  - JSONPath: .spec.classRef.name
    name: CLASS
    type: string
  - JSONPath: .spec.engineVersion
    name: VERSION
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  group: database.aws.crossplane.io
  names:
    kind: RDSInstance
    plural: rdsinstances
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            claimRef:
              type: object
            class:
              type: string
            classRef:
              type: object
            connectionSecretRef:
              type: object
            engine:
              type: string
            engineVersion:
              type: string
            masterUsername:
              type: string
            providerRef:
              type: object
            reclaimPolicy:
              type: string
            securityGroups:
              items:
                type: string
              type: array
            size:
              format: int64
              type: integer
            subnetGroupName:
              type: string
          required:
          - masterUsername
          - engine
          - class
          - size
          - providerRef
          type: object
        status:
          properties:
            endpoint:
              type: string
            instanceName:
              type: string
            message:
              type: string
            providerID:
              type: string
            state:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
