apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: mysqlservers.database.azure.conductor.io
spec:
  group: database.azure.conductor.io
  names:
    kind: MysqlServer
    plural: mysqlservers
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            adminLoginName:
              type: string
            connectionSecretRef:
              type: object
            location:
              type: string
            pricingTier:
              properties:
                family:
                  type: string
                tier:
                  type: string
                vcores:
                  format: int64
                  type: integer
              required:
              - tier
              - vcores
              - family
              type: object
            providerRef:
              type: object
            resourceGroupName:
              type: string
            sslEnforced:
              type: boolean
            storageProfile:
              properties:
                backupRetentionDays:
                  format: int64
                  type: integer
                geoRedundantBackup:
                  type: boolean
                storageGB:
                  format: int64
                  type: integer
              required:
              - storageGB
              type: object
            version:
              type: string
          required:
          - providerRef
          - resourceGroupName
          - location
          - pricingTier
          - storageProfile
          - adminLoginName
          - version
          type: object
        status:
          properties:
            endpoint:
              type: string
            message:
              type: string
            providerID:
              type: string
            runningOperation:
              type: string
            state:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
