apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: rdsinstances.database.aws.conductor.io
spec:
  group: database.aws.conductor.io
  names:
    kind: RDSInstance
    plural: rdsinstances
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            backupretentionperiod:
              format: int64
              type: integer
            class:
              type: string
            encrypted:
              type: boolean
            engine:
              type: string
            iops:
              format: int64
              type: integer
            masterPasswordSecretRef:
              type: object
            masterUsername:
              type: string
            multiaz:
              type: boolean
            publicaccess:
              type: boolean
            size:
              format: int64
              type: integer
            storagetype:
              type: string
          required:
          - masterUsername
          - masterPasswordSecretRef
          - engine
          - class
          - size
          type: object
        status:
          properties:
            message:
              type: string
            providerID:
              type: string
            state:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
