apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: gcpbuckets.storage.gcp.crossplane.io
spec:
  group: storage.gcp.crossplane.io
  names:
    kind: GCPBucket
    plural: gcpbuckets
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            claimRef:
              type: object
            classRef:
              type: object
            connectionSecretNameOverride:
              type: string
            location:
              description: Location - See authoritative list https://developers.google.com/storage/docs/bucket-locations
                Which you use is dependent on whether it's multi_region or not.
              type: string
            name:
              type: string
            predefinedACL:
              description: 'PredefinedACL One of: private, authenticatedRead, projectPrivate,
                publicRead, publicReadWrite'
              type: string
            providerRef:
              type: object
            storageClass:
              description: StorageClass one of MULTI_REGIONAL, REGIONAL, STANDARD,
                NEARLINE, COLDLINE, and DURABLE_REDUCED_AVAILABILITY. If this value
                is not specified when the bucket is created, it will default to STANDARD
              type: string
            versioning:
              type: boolean
          required:
          - providerRef
          type: object
        status:
          properties:
            connectionSecretRef:
              description: the external ID to identify this resource in the cloud
                provider
              type: object
            message:
              type: string
            providerID:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
