{{ if .Capabilities.APIVersions.Has "pkg.crossplane.io/v1alpha1" }}
{{ if or (eq .Values.giantswarm.kubernetes.provider.kind "aws") (eq .Values.giantswarm.kubernetes.provider.kind "capa") }}
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: "{{- include "provider.contribAws.name" . }}"
  namespace: {{ .Release.Namespace | quote }}
spec:
  {{- with .Values.giantswarm.crossplane.providers.contribAws.controllerConfig.args }}
  args:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  image: "{{ .Values.giantswarm.images.registry }}/{{ .Values.giantswarm.crossplane.providers.contribAws.controllerConfig.image }}:{{ .Values.giantswarm.crossplane.providers.contribAws.version }}"
  serviceAccountName: "{{- include "provider.contribAws.name" . }}"
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: "{{- include "provider.upboundAws.name" . }}"
  namespace: {{ .Release.Namespace | quote }}
spec:
  {{- with .Values.giantswarm.crossplane.providers.upboundAws.controllerConfig.args }}
  args:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  image: "{{ .Values.giantswarm.images.registry }}/{{ .Values.giantswarm.crossplane.providers.upboundAws.controllerConfig.image }}:{{ .Values.giantswarm.crossplane.providers.upboundAws.version }}"
  serviceAccountName: "{{- include "provider.upboundAws.name" . }}"
{{ end }}
{{ end }}
