{{ if eq .Values.giantswarm.kubernetes.provider.kind "aws" }}
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: "{{- include "provider.aws.name" . }}"
  namespace: {{ .Release.Namespace | quote }}
spec:
  {{- with .Values.giantswarm.crossplane.providers.aws.controllerConfig.args }}
  args:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  image: "{{ .Values.giantswarm.images.registry }}/{{ .Values.giantswarm.crossplane.providers.aws.controllerConfig.image }}:{{ .Values.giantswarm.crossplane.providers.aws.version }}"
{{ end }}