{{ if eq .Values.giantswarm.kubernetes.provider.kind "aws" }}
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "labels.selector" . | nindent 4 }}
spec:
  ignoreCrossplaneConstraints: {{ .Values.giantswarm.crossplane.providers.config.ignoreCrossplaneConstraints }}
  package: "xpkg.upbound.io/crossplane-contrib/provider-aws:{{ .Values.giantswarm.crossplane.providers.aws.version }}"
  packagePullPolicy: {{ .Values.giantswarm.crossplane.providers.config.packagePullPolicy }}
  revisionActivationPolicy: {{ .Values.giantswarm.crossplane.providers.config.revisionActivationPolicy }}
  revisionHistoryLimit: {{ .Values.giantswarm.crossplane.providers.config.revisionHistoryLimit }}
  skipDependencyResolution: {{ .Values.giantswarm.crossplane.providers.config.skipDependencyResolution }}
{{ end }}
