{{ if .Values.giantswarm.providers.azure.enabled }}
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-azure
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "labels.selector" . | nindent 4 }}
spec:
  ignoreCrossplaneConstraints: {{ .Values.giantswarm.providers.config.ignoreCrossplaneConstraints }}
  package: "xpkg.upbound.io/crossplane-contrib/provider-azure:{{ .Values.giantswarm.providers.azure.version }}"
  packagePullPolicy: {{ .Values.giantswarm.providers.config.packagePullPolicy }}
  revisionActivationPolicy: {{ .Values.giantswarm.providers.config.revisionActivationPolicy }}
  revisionHistoryLimit: {{ .Values.giantswarm.providers.config.revisionHistoryLimit }}
  skipDependencyResolution: {{ .Values.giantswarm.providers.config.skipDependencyResolution }}
{{ end }}
