{{ if or (eq .Values.giantswarm.kubernetes.provider.kind "aws") (eq .Values.giantswarm.kubernetes.provider.kind "capa") }}
{{ if .Values.giantswarm.crossplane.providers.contribAws.enabled }}
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: "{{- include "provider.contribAws.name" . }}"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "labels.selector" . | nindent 4 }}
spec:
  controllerConfigRef:
    name: "{{- include "provider.contribAws.name" . }}"
  ignoreCrossplaneConstraints: {{ .Values.giantswarm.crossplane.providers.config.ignoreCrossplaneConstraints }}
  package: "xpkg.upbound.io/crossplane-contrib/provider-aws:{{ .Values.giantswarm.crossplane.providers.contribAws.version }}"
  packagePullPolicy: {{ .Values.giantswarm.crossplane.providers.config.packagePullPolicy }}
  revisionActivationPolicy: {{ .Values.giantswarm.crossplane.providers.config.revisionActivationPolicy }}
  revisionHistoryLimit: {{ .Values.giantswarm.crossplane.providers.config.revisionHistoryLimit }}
  skipDependencyResolution: {{ .Values.giantswarm.crossplane.providers.config.skipDependencyResolution }}
{{ end }}
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: "{{- include "provider.upboundAws.name" . }}"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "labels.selector" . | nindent 4 }}
spec:
  controllerConfigRef:
    name: "{{- include "provider.upboundAws.name" . }}"
  ignoreCrossplaneConstraints: {{ .Values.giantswarm.crossplane.providers.config.ignoreCrossplaneConstraints }}
  package: "xpkg.upbound.io/upbound/provider-aws:{{ .Values.giantswarm.crossplane.providers.upboundAws.version }}"
  packagePullPolicy: {{ .Values.giantswarm.crossplane.providers.config.packagePullPolicy }}
  revisionActivationPolicy: {{ .Values.giantswarm.crossplane.providers.config.revisionActivationPolicy }}
  revisionHistoryLimit: {{ .Values.giantswarm.crossplane.providers.config.revisionHistoryLimit }}
  skipDependencyResolution: {{ .Values.giantswarm.crossplane.providers.config.skipDependencyResolution }}
{{ end }}
