apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: s3buckets.storage.aws.conductor.io
spec:
  group: storage.aws.conductor.io
  names:
    kind: S3Bucket
    plural: s3buckets
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            cannedACL:
              type: string
            connectionSecretNameOverride:
              type: string
            name:
              type: string
            providerRef:
              type: object
            region:
              type: string
            versioning:
              type: boolean
          required:
          - versioning
          - providerRef
          type: object
        status:
          properties:
            connectionSecretRef:
              type: object
            message:
              type: string
            providerID:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
