
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: gkeclusterclasses.compute.gcp.crossplane.io
spec:
  additionalPrinterColumns:
  - JSONPath: .specTemplate.providerRef.name
    name: PROVIDER-REF
    type: string
  - JSONPath: .specTemplate.reclaimPolicy
    name: RECLAIM-POLICY
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  group: compute.gcp.crossplane.io
  names:
    kind: GKEClusterClass
    plural: gkeclusterclasses
  scope: ""
  subresources: {}
  validation:
    openAPIV3Schema:
      description: GKEClusterClass is the Schema for the resource class
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        specTemplate:
          description: GKEClusterClassSpecTemplate is the Schema for the resource
            class
          properties:
            addons:
              items:
                type: string
              type: array
            async:
              type: boolean
            clusterIPV4CIDR:
              type: string
            clusterSecondaryRangeName:
              type: string
            clusterVersion:
              type: string
            createSubnetwork:
              type: boolean
            diskSize:
              type: string
            enableAutorepair:
              type: boolean
            enableAutoscaling:
              type: boolean
            enableAutoupgrade:
              type: boolean
            enableBasicAuth:
              type: boolean
            enableCloudEndpoints:
              type: boolean
            enableCloudLogging:
              type: boolean
            enableCloudMonitoring:
              type: boolean
            enableIPAlias:
              type: boolean
            enableKubernetesAlpha:
              type: boolean
            enableLegacyAuthorization:
              type: boolean
            enableNetworkPolicy:
              type: boolean
            imageType:
              type: string
            labels:
              additionalProperties:
                type: string
              type: object
            localSSDCount:
              format: int64
              type: integer
            machineType:
              type: string
            maintenanceWindow:
              type: string
            maxNodes:
              format: int64
              type: integer
            maxNodesPerPool:
              format: int64
              type: integer
            minCPUPlatform:
              type: string
            minNodes:
              format: int64
              type: integer
            network:
              type: string
            noIssueClientCertificates:
              type: boolean
            nodeIPV4CIDR:
              type: string
            nodeLabels:
              items:
                type: string
              type: array
            nodeLocations:
              items:
                type: string
              type: array
            nodeTaints:
              items:
                type: string
              type: array
            nodeVersion:
              items:
                type: string
              type: array
            numNodes:
              format: int64
              type: integer
            password:
              type: string
            preemtible:
              type: boolean
            providerRef:
              description: ObjectReference contains enough information to let you
                inspect or modify the referred object.
              properties:
                apiVersion:
                  description: API version of the referent.
                  type: string
                fieldPath:
                  description: 'If referring to a piece of an object instead of an
                    entire object, this string should contain a valid JSON/Go field
                    access statement, such as desiredState.manifest.containers[2].
                    For example, if the object reference is to a container within
                    a pod, this would take on a value like: "spec.containers{name}"
                    (where "name" refers to the name of the container that triggered
                    the event) or if no container name is specified "spec.containers[2]"
                    (container with index 2 in this pod). This syntax is chosen only
                    to have some well-defined way of referencing a part of an object.
                    TODO: this design is not final and this field is subject to change
                    in the future.'
                  type: string
                kind:
                  description: 'Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
                  type: string
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                  type: string
                namespace:
                  description: 'Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/'
                  type: string
                resourceVersion:
                  description: 'Specific resourceVersion to which this reference is
                    made, if any. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#concurrency-control-and-consistency'
                  type: string
                uid:
                  description: 'UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids'
                  type: string
              type: object
            reclaimPolicy:
              description: A ReclaimPolicy determines what should happen to managed
                resources when their bound resource claims are deleted.
              type: string
            scopes:
              items:
                type: string
              type: array
            serviceAccount:
              type: string
            serviceIPV4CIDR:
              type: string
            serviceSecondaryRangeName:
              type: string
            subnetwork:
              type: string
            tags:
              items:
                type: string
              type: array
            username:
              type: string
            zone:
              type: string
          required:
          - providerRef
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
