version: 2.1

orbs:
  architect: giantswarm/architect@4.15.0

workflows:
  build:
    jobs:
      # Ensure that for every commit to master and for every
      # release tag, there is an app version in the catalog.
      - architect/push-to-app-catalog:
          context: architect
          name: push-to-app-catalog-master
          app_catalog: "giantswarm-playground-catalog"
          app_catalog_test: "giantswarm-playground-test-catalog"
          chart: "crossplane"
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/

      # Ensure that for every commit (branch other than master)
      # there is an app version in the test catalog.
      - architect/push-to-app-catalog:
          context: architect
          name: push-to-app-catalog-pr
          app_catalog: "giantswarm-playground-catalog"
          app_catalog_test: "giantswarm-playground-test-catalog"
          chart: "crossplane"
          filters:
            branches:
              ignore: master
