apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: cloudsqlinstances.database.gcp.conductor.io
spec:
  group: database.gcp.conductor.io
  names:
    kind: CloudsqlInstance
    plural: cloudsqlinstances
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            databaseVersion:
              type: string
            projectID:
              type: string
            region:
              type: string
            storageType:
              type: string
            tier:
              type: string
          required:
          - projectID
          - tier
          - region
          - databaseVersion
          - storageType
          type: object
        status:
          properties:
            message:
              type: string
            providerID:
              type: string
            state:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
