apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: gcpbuckets.storage.gcp.conductor.io
spec:
  group: storage.gcp.conductor.io
  names:
    kind: GCPBucket
    plural: gcpbuckets
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            location:
              type: string
            name:
              type: string
            predefinedACL:
              type: string
            providerRef:
              type: object
            storageClass:
              type: string
            versioning:
              type: boolean
          required:
          - providerRef
          type: object
        status:
          properties:
            connectionSecretRef:
              type: object
            message:
              type: string
            providerID:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
