apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: resourcegroups.azure.crossplane.io
spec:
  group: azure.crossplane.io
  names:
    kind: ResourceGroup
    plural: resourcegroups
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            claimRef:
              type: object
            classRef:
              type: object
            location:
              description: See official list of valid regions - https://azure.microsoft.com/en-us/global-infrastructure/regions/
              type: string
            name:
              description: Name of the resource group
              type: string
            providerRef:
              type: object
            reclaimPolicy:
              type: string
            writeConnectionSecretToRef:
              type: object
          required:
          - providerRef
          type: object
        status:
          properties:
            name:
              type: string
          required:
          - name
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
