giantswarm:
  images:
    registry: docker.io
    crossplane:
      image: giantswarm/crossplane
    pullPolicy: IfNotPresent

  kubernetes:
    provider:
      kind: ""

  crossplane:
    providers:
      config:
        ignoreCrossplaneConstraints: false
        packagePullPolicy: IfNotPresent
        revisionActivationPolicy: Automatic
        revisionHistoryLimit: 0
        skipDependencyResolution: false

      upboundAws:
        version: v0.27.0
        controllerConfig:
          args:
            - --debug
          image: giantswarm/upbound-provider-aws

      contribAws:
        version: v0.35.0
        controllerConfig:
          args:
            - --debug
          image: giantswarm/crossplane-provider-aws

      upboundAzure:
        version: v0.26.0
        controllerConfig:
          args:
            - --debug
          image: giantswarm/upbound-provider-azure

      upboundGcp:
        version: v0.26.0
        controllerConfig:
          args:
            - --debug
          image: giantswarm/upbound-provider-gcp

  crds:
    install: true
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "265Mi"
        cpu: "500m"

replicas: 1

deploymentStrategy: RollingUpdate

nodeSelector: {}
tolerations: {}
affinity: {}

# -- Custom labels to add into metadata
customLabels: {}

# -- Custom annotations to add to the Crossplane deployment and pod
customAnnotations: {}

# -- Custom annotations to add to the serviceaccount of Crossplane
serviceAccount:
  customAnnotations: {}

leaderElection: true
args: {}

provider:
  packages: []

configuration:
  packages: []

imagePullSecrets: {}

registryCaBundleConfig: {}

webhooks:
  enabled: false

rbacManager:
  deploy: true
  skipAggregatedClusterRoles: false
  replicas: 1
  managementPolicy: All
  leaderElection: true
  args: {}
  nodeSelector: {}
  tolerations: {}
  affinity: {}

priorityClassName: ""

resourcesCrossplane:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

securityContextCrossplane:
  runAsUser: 65532
  runAsGroup: 65532
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

packageCache:
  medium: ""
  sizeLimit: 5Mi
  pvc: ""

resourcesRBACManager:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

securityContextRBACManager:
  runAsUser: 65532
  runAsGroup: 65532
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

metrics:
  enabled: false

extraEnvVarsCrossplane: {}

extraEnvVarsRBACManager: {}

podSecurityContextCrossplane: {}

podSecurityContextRBACManager: {}
