apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: resourceclasses.core.crossplane.io
spec:
  additionalPrinterColumns:
  - JSONPath: .provisioner
    name: PROVISIONER
    type: string
  - JSONPath: .providerRef.name
    name: PROVIDER-REF
    type: string
  - JSONPath: .reclaimPolicy
    name: RECLAIM-POLICY
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  group: core.crossplane.io
  names:
    kind: ResourceClass
    plural: resourceclasses
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        parameters:
          type: object
        providerRef:
          type: object
        provisioner:
          type: string
        reclaimPolicy:
          type: string
      required:
      - provisioner
      - providerRef
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
