apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: providers.gcp.conductor.io
spec:
  group: gcp.conductor.io
  names:
    kind: Provider
    plural: providers
    shortNames:
    - creds
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            credentialsSecretRef:
              type: object
            projectID:
              type: string
            requiredPermissions:
              type: array
              items:
                type: string
          required:
          - credentialsSecretRef
          - projectID
        status:
          type: object
  version: v1alpha1
