{{- if .Values.rbacManager.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "name" . }}-rbac-manager
  labels:
    app: {{ template "name" . }}-rbac-manager
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "name" . }}-rbac-manager
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.deploymentStrategy }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}-rbac-manager
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      {{- if not .Values.hostedConfig.enabled }}
      serviceAccountName: rbac-manager
      {{- end }}
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        args:
        - rbac
        {{- if .Values.rbacManager.managementPolicy }}
        - --manage={{ .Values.rbacManager.managementPolicy }}
        {{- end }}
        {{- range $arg := .Values.args }}
        - {{ $arg }}
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        resources:
          {{- toYaml .Values.resourcesRBACManager | nindent 12 }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      {{- if .Values.hostedConfig.enabled }}
        env:
          - name: KUBERNETES_SERVICE_HOST
            value: {{ .Values.hostedConfig.tenantKubernetesServiceHost | quote }}
          - name: KUBERNETES_SERVICE_PORT
            value: {{ .Values.hostedConfig.tenantKubernetesServicePort | quote }}
        volumeMounts:
          - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
            name: sa-token
            readOnly: true
      automountServiceAccountToken: false
      serviceAccount: ""
      serviceAccountName: ""
      volumes:
        - name: sa-token
          secret:
            defaultMode: 420
            secretName: {{ .Values.hostedConfig.rbacManagerSATokenSecret | quote }}
      {{- end }}
{{- end}}
