apiVersion: v1
appVersion: 0.0.1
description: Crossplane is an open source Kubernetes add-on that extends any cluster with the ability to provision and manage cloud infrastructure, services, and applications using kubectl, GitOps, or any tool that works with the Kubernetes API.
name: crossplane
version: 0.0.1
icon: https://crossplane.io/images/favicon_192x192.png
home: https://crossplane.io
maintainers:
  - name: Crossplane Maintainers
    email: info@crossplane.io
source:
- https://github.com/crossplane/crossplane
- https://github.com/crossplane/crossplane-runtime
- https://github.com/crossplane/provider-aws
- https://github.com/crossplane/provider-azure
- https://github.com/crossplane/provider-gcp
- https://github.com/crossplane/provider-rook
keywords:
- cloud
- infrastructure
- services
- application
- database
- cache
- bucket
- infra
- app
- ops
- oam
- gcp
- azure
- aws
- alibaba
- cloudsql
- rds
- s3
- azuredatabase
- asparadb
- gke
- aks
- eks
