apiVersion: v1
appVersion: 0.0.1
description: Crossplane, the open source multicloud control plane, allows you to manage your cloud-native applications and infrastructure across environments, clusters, regions and clouds.
name: crossplane
version: 0.0.1
icon: https://crossplane.io/images/favicon_192x192.png
home: https://crossplane.io
maintainers:
  - name: Crossplane Maintainers
    email: info@crossplane.io
source:
- https://github.com/crossplaneio/crossplane
- https://github.com/crossplaneio/crossplane-runtime
- https://github.com/crossplaneio/stack-aws
- https://github.com/crossplaneio/stack-azure
- https://github.com/crossplaneio/stack-gcp
- https://github.com/crossplaneio/stack-rook
keywords:
- clusters as cattle
- infrastructure
- iac
- workloads
- gcp
- azure
- aws
- rds
- cloudsql
- gke
- aks
- eks
