apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: s3buckets.storage.aws.crossplane.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.classRef.name
    name: CLASS
    type: string
  - JSONPath: .spec.cannedACL
    name: PREDEFINED-ACL
    type: string
  - JSONPath: .spec.localPermission
    name: LOCAL-PERMISSION
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  group: storage.aws.crossplane.io
  names:
    kind: S3Bucket
    plural: s3buckets
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            cannedACL:
              enum:
              - private
              - public-read
              - public-read-write
              - authenticated-read
              - log-delivery-write
              - aws-exec-read
              type: string
            claimRef:
              type: object
            classRef:
              type: object
            connectionSecretNameOverride:
              maxLength: 255
              minLength: 1
              type: string
            localPermission:
              enum:
              - Read
              - Write
              - ReadWrite
              type: string
            name:
              maxLength: 63
              minLength: 3
              type: string
            providerRef:
              type: object
            reclaimPolicy:
              type: string
            region:
              type: string
            versioning:
              type: boolean
          required:
          - region
          - localPermission
          - providerRef
          type: object
        status:
          properties:
            connectionSecretRef:
              type: object
            iamUsername:
              type: string
            lastLocalPermission:
              type: string
            lastUserPolicyVersion:
              format: int64
              type: integer
            message:
              type: string
            providerID:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
