apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: mysqlservers.database.azure.crossplane.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.bindingPhase
    name: STATUS
    type: string
  - JSONPath: .status.state
    name: STATE
    type: string
  - JSONPath: .spec.classRef.name
    name: CLASS
    type: string
  - JSONPath: .spec.version
    name: VERSION
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  group: database.azure.crossplane.io
  names:
    kind: MysqlServer
    plural: mysqlservers
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            adminLoginName:
              type: string
            claimRef:
              description: Kubernetes object references
              type: object
            classRef:
              type: object
            connectionSecretRef:
              type: object
            location:
              type: string
            pricingTier:
              properties:
                family:
                  type: string
                tier:
                  type: string
                vcores:
                  format: int64
                  type: integer
              required:
              - tier
              - vcores
              - family
              type: object
            providerRef:
              type: object
            reclaimPolicy:
              description: ReclaimPolicy identifies how to handle the cloud resource
                after the deletion of this type
              type: string
            resourceGroupName:
              type: string
            sslEnforced:
              type: boolean
            storageProfile:
              properties:
                backupRetentionDays:
                  format: int64
                  type: integer
                geoRedundantBackup:
                  type: boolean
                storageGB:
                  format: int64
                  type: integer
              required:
              - storageGB
              type: object
            version:
              type: string
          required:
          - resourceGroupName
          - location
          - pricingTier
          - storageProfile
          - adminLoginName
          - version
          - providerRef
          type: object
        status:
          properties:
            endpoint:
              description: Endpoint of the MySQL Server instance used in connection
                strings
              type: string
            message:
              type: string
            providerID:
              description: the external ID to identify this resource in the cloud
                provider
              type: string
            runningOperation:
              description: RunningOperation stores any current long running operation
                for this instance across reconciliation attempts.  This will be a
                serialized Azure MySQL Server API object that will be used to check
                the status and completion of the operation during each reconciliation.
                Once the operation has completed, this field will be cleared out.
              type: string
            runningOperationType:
              description: RunningOperationType is the type of the currently running
                operation
              type: string
            state:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
