personas:
  deploy: true

clusterStacks:
  aws:
    version: master
    deploy: false
  gcp:
    version: master
    deploy: false
  azure:
    version: master
    deploy: false
  rook:
    version: master
    deploy: false
