apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: kubernetesapplications.workload.crossplane.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.clusterRef.name
    name: CLUSTER
    type: string
  - JSONPath: .status.state
    name: STATUS
    type: string
  - JSONPath: .status.desiredResources
    name: DESIRED
    type: integer
  - JSONPath: .status.submittedResources
    name: SUBMITTED
    type: integer
  group: workload.crossplane.io
  names:
    kind: KubernetesApplication
    plural: kubernetesapplications
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            clusterSelector:
              description: ClusterSelector selects the clusters to which this application
                may be scheduled.
              type: object
            resourceSelector:
              description: ResourceSelector selects the KubernetesApplicationResources
                that are managed by this KubernetesApplication. Note that a KubernetesApplication
                will never adopt orphaned KubernetesApplicationResources, and thus
                this selector serves only to help match a KubernetesApplication to
                its KubernetesApplicationResources.
              type: object
            resourceTemplates:
              description: ResourceTemplates specifies a set of Kubernetes application
                resources managed by this application.
              items:
                properties:
                  metadata:
                    type: object
                  spec:
                    properties:
                      secrets:
                        description: Secrets upon which this application resource
                          depends. These secrets will be propagated to the Kubernetes
                          cluster to which this application is scheduled.
                        items:
                          type: object
                        type: array
                      template:
                        description: A Template for a Kubernetes resource to be submitted
                          to the KubernetesCluster to which this application resource
                          is scheduled. The resource must be understood by the KubernetesCluster.
                          Crossplane requires only that the resource contains standard
                          Kubernetes type and object metadata.
                        type: object
                    required:
                    - template
                    type: object
                type: object
              type: array
          required:
          - resourceSelector
          - resourceTemplates
          type: object
        status:
          properties:
            clusterRef:
              description: Cluster to which this application has been scheduled.
              type: object
            desiredResources:
              description: Desired resources of this application, i.e. the number
                of resources that match this application's resource selector.
              format: int64
              type: integer
            state:
              description: State of the application.
              type: string
            submittedResources:
              description: Submitted resources of this workload, i.e. the subset of
                desired resources that have been successfully submitted to their scheduled
                Kubernetes cluster.
              format: int64
              type: integer
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
