apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "name" . }}-stack-manager
  labels:
    app: {{ template "name" . }}-stack-manager
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "name" . }}-stack-manager
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.deploymentStrategy }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}-stack-manager
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: stack-manager
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        args:
        - stack
        - manage
        {{- range $arg := .Values.args }}
        - {{ $arg }}
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        env:
        # The pod name to pass with the downward API
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        # The pod namespace to pass with the downward API
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- if .Values.tenantKubeconfigSecret != "" }}
        - name: TENANT_KUBECONFIG
          value: /var/run/secrets/tenant/config
        {{- end }}
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
      {{- if .Values.tenantKubeconfigSecret != "" }}
        volumeMounts:
          - mountPath: /var/run/secrets/tenant
            name: tenant-config
            readOnly: true
      volumes:
        - name: tenant-config
          secret:
            defaultMode: 420
            secretName: {{ .Values.tenantKubeconfigSecret | quote }}
      {{- end }}
