apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: eksclusters.compute.aws.conductor.io
spec:
  group: compute.aws.conductor.io
  names:
    kind: EKSCluster
    plural: eksclusters
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            cliInput:
              type: string
            clientRequestToken:
              type: string
            clusterVersion:
              type: string
            connectionSecretRef:
              type: object
            generateCLISkeleton:
              type: string
            providerRef:
              type: object
            reclaimPolicy:
              type: string
            roleARN:
              type: string
            securityGroups:
              items:
                type: string
              type: array
            subnetIds:
              items:
                type: string
              type: array
          required:
          - roleARN
          - subnetIds
          - securityGroups
          - clientRequestToken
          - clusterVersion
          - providerRef
          - connectionSecretRef
          type: object
        status:
          properties:
            message:
              type: string
            state:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
