apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: kubernetesclusters.compute.crossplane.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.bindingPhase
    name: STATUS
    type: string
  - JSONPath: .spec.classReference.name
    name: CLASS
    type: string
  - JSONPath: .spec.classReference.name
    name: CLUSTER-CLASS
    type: string
  - JSONPath: .spec.resourceName.name
    name: CLUSTER-REF
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  group: compute.crossplane.io
  names:
    kind: KubernetesCluster
    plural: kubernetesclusters
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            classReference:
              type: object
            clusterVersion:
              type: string
            resourceName:
              type: object
            selector:
              type: object
          type: object
        status:
          properties:
            credentialsSecret:
              type: object
            provisioner:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
