apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: workloads.compute.crossplane.io
spec:
  group: compute.crossplane.io
  names:
    kind: Workload
    plural: workloads
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            resources:
              items:
                properties:
                  apiVersion:
                    type: string
                  fieldPath:
                    type: string
                  kind:
                    type: string
                  name:
                    type: string
                  namespace:
                    type: string
                  resourceVersion:
                    type: string
                  secretName:
                    type: string
                  uid:
                    type: string
                required:
                - secretName
                type: object
              type: array
            targetCluster:
              type: object
            targetDeployment:
              type: object
            targetNamespace:
              type: string
            targetService:
              type: object
          required:
          - targetCluster
          - targetNamespace
          - targetDeployment
          - targetService
          - resources
          type: object
        status:
          properties:
            deployment:
              type: object
            service:
              type: object
            state:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
